# Bearded Theme — Aquarelle Lilac

# Background and foreground colors
background = #252433
foreground = #d9d8e4

cursor-color = #9587ff
selection-background = #bcb1f1
selection-foreground = #252433

# Standard colors
palette = 0=#201f2c
palette = 1=#eca099
palette = 2=#c3e5a1
palette = 3=#f3e1ac
palette = 4=#afd9ec
palette = 5=#bcb1f1
palette = 6=#a9edd9
palette = 7=#bcbbce

# Bright colors
palette = 8=#5c5a7d
palette = 9=#f3aabc
palette = 10=#d1e796
palette = 11=#f0bba2
palette = 12=#73bee9
palette = 13=#edc1ea
palette = 14=#a9edd9
palette = 15=#d9d8e4
